name: glowbook
description: Trippy neon mandala drawing app - Sprint 1 skeleton
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.2.3
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
    # - assets/sounds/
    # - assets/icons/
    # - assets/brushes/
    # - assets/textures/
